version: '3'
services:
  mysql:
    image: mysql:5.6.27
    ports:
      - "127.0.0.1:7010:3306"
    volumes:
      - mysqldatadesignpattern:/var/lib/mysql
      - ./resource/docker/initdb:/docker-entrypoint-initdb.d  
    container_name: mysql-designpattern
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      TZ: Asia/Jakarta
    networks:
      - designpattern-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 7011:8080
    networks:
      - designpattern-net

volumes:
  mysqldatadesignpattern:
    driver: local

networks:
  designpattern-net:
    driver: bridge